let currentConfig=null,lastRadarRefresh=0,radarRefreshInFlight=false,toastTimer=null,streamLoadedOnce=false;
const byId=id=>document.getElementById(id);
const arr=v=>Array.isArray(v)?v:[];
function setText(id,text){const el=byId(id);if(el)el.textContent=text;}
function setStatus(msg,state){const el=byId('saveState');if(!el)return;el.textContent=msg||'';state?el.dataset.state=state:delete el.dataset.state;}
function setStreamStatus(msg,state){setText('streamStatusText',msg||'');setText('panelStreamStatus',msg||'ok');document.body.classList.toggle('is-loading',state==='loading');document.body.classList.toggle('is-reconnecting',state==='reconnect');document.body.classList.toggle('stream-missing',state==='missing'||state==='offline');}
function showToast(msg,state='info'){const t=byId('toast');if(!t||!msg)return;t.textContent=msg;t.dataset.state=state;t.classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.add('hidden'),4200);}
function tick(){const d=new Date(),hm=d.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}),sec=d.toLocaleTimeString('de-DE',{second:'2-digit'});const el=byId('clock');if(el)el.innerHTML=`<span class="clock-hm">${hm}</span><span class="clock-sec">${sec}</span>`;}
setInterval(tick,1000);tick();
function makeCell(text,cls){const td=document.createElement('td');td.textContent=text;if(cls)td.className=cls;return td;}
function shortenTarget(v,max=18){const s=String(v||'-').replace(/\s+/g,' ').replace(/^Bielefeld\s+/i,'').replace(/^BI-\s*/i,'').trim();return s.length>max?s.slice(0,max-1).trim()+'…':s;}
function renderBoards(boards){const root=byId('boards');if(!root)return;root.replaceChildren();arr(boards).slice(0,2).forEach(board=>{const card=document.createElement('div');card.className='board';const h=document.createElement('h3');h.textContent=board.title||'HALT';card.appendChild(h);const table=document.createElement('table'),head=document.createElement('thead'),hr=document.createElement('tr');['Linie','Ziel','Zeit'].forEach((x,i)=>{const th=document.createElement('th');th.textContent=x;if(i===2)th.className='time';hr.appendChild(th);});head.appendChild(hr);table.appendChild(head);const body=document.createElement('tbody'),rows=arr(board.rows).slice(0,3);if(rows.length){rows.forEach(row=>{const tr=document.createElement('tr');tr.appendChild(makeCell(row.line||'-'));tr.appendChild(makeCell(shortenTarget(row.target),'target'));tr.appendChild(makeCell(row.mins||'-','time'));body.appendChild(tr);});}else{const tr=document.createElement('tr'),td=makeCell('keine Abfahrten','empty');td.colSpan=3;tr.appendChild(td);body.appendChild(tr);}table.appendChild(body);card.appendChild(table);root.appendChild(card);});}
function applyUi(cfg){const ui=cfg?.ui||{};document.body.classList.toggle('hide-weather',!(ui.weather&&ui.weather.enabled));document.body.classList.toggle('hide-radar',!(ui.radar&&ui.radar.enabled));document.body.classList.toggle('hide-transit',!(ui.transit&&ui.transit.enabled));document.body.classList.toggle('hide-system',!(ui.system&&ui.system.enabled));const radar=byId('radar');if(radar&&ui.radar&&ui.radar.height){radar.style.height=Math.max(120,Math.min(260,Number(ui.radar.height)||170))+'px';}}
function lon2tile(lon,z){return Math.floor((lon+180)/360*Math.pow(2,z));}
function lat2tile(lat,z){const r=lat*Math.PI/180;return Math.floor((1-Math.log(Math.tan(r)+1/Math.cos(r))/Math.PI)/2*Math.pow(2,z));}
function tileUrl(t,z,x,y){return t.replaceAll('{z}',String(z)).replaceAll('{x}',String(x)).replaceAll('{y}',String(y));}
function setRadarStatus(text){const map=byId('radar-map');if(!map)return;let s=map.querySelector('.radar-status');if(!s){s=document.createElement('div');s.className='radar-status';map.appendChild(s);}s.textContent=text;}
function renderRadar(meta){const map=byId('radar-map');if(!map)return;map.replaceChildren();const label=meta?.label||'Bielefeld';setText('radarLabel',label);if(!meta||!meta.ok||!meta.tile_url){map.classList.add('radar-offline');setRadarStatus('offline · '+(meta?.error||'keine Daten'));return;}map.classList.remove('radar-offline');const z=Number(meta.zoom||10),lat=Number(meta.latitude||52.0302),lon=Number(meta.longitude||8.5325),cx=lon2tile(lon,z),cy=lat2tile(lat,z),grid=document.createElement('div');grid.className='radar-grid';for(let dy=-1;dy<=1;dy++){for(let dx=-1;dx<=1;dx++){const x=cx+dx,y=cy+dy,cell=document.createElement('div'),base=document.createElement('img'),rain=document.createElement('img');cell.className='radar-cell';base.alt='';base.loading='lazy';base.decoding='async';base.src=`https://tile.openstreetmap.org/${z}/${x}/${y}.png`;rain.alt='';rain.loading='lazy';rain.decoding='async';rain.className='rain';rain.src=tileUrl(meta.tile_url,z,x,y);cell.append(base,rain);grid.appendChild(cell);}}map.appendChild(grid);setRadarStatus(label+' · aktuell');}
async function refreshRadar(force){const ui=currentConfig?.ui||{};if(ui.radar&&ui.radar.enabled===false)return;const now=Date.now(),sec=ui.radar&&ui.radar.refresh_seconds?Number(ui.radar.refresh_seconds):300,interval=Math.max(sec,60)*1000;if(!force&&now-lastRadarRefresh<interval)return;if(radarRefreshInFlight)return;radarRefreshInFlight=true;try{const r=await fetch('/api/radar?_='+now,{cache:'no-store'});renderRadar(await r.json());lastRadarRefresh=Date.now();}catch(e){renderRadar({ok:false,error:e.message||'Netzwerkfehler'});lastRadarRefresh=Date.now();}finally{radarRefreshInFlight=false;}}
function reloadStream(){const live=byId('live'),stream=currentConfig?.stream?.url||live?.src;if(!live)return;if(!stream){setStreamStatus('Livestream-URL fehlt','missing');showToast('Livestream-URL fehlt','error');return;}streamLoadedOnce=false;setStreamStatus('Livestream wird neu geladen','loading');live.src='about:blank';setTimeout(()=>{live.src=stream;},80);}
async function pull(){try{const r=await fetch('/api/state?_='+Date.now(),{cache:'no-store'}),d=await r.json(),cfg=d.config||{};currentConfig=cfg;applyUi(cfg);const stream=cfg.stream?.url||'',live=byId('live');if(stream&&live&&live.src!==stream){streamLoadedOnce=false;setStreamStatus('Livestream wird geladen','loading');live.src=stream;}else if(!stream){setStreamStatus('Livestream-URL fehlt','missing');}else if(streamLoadedOnce){setStreamStatus('Livestream verbunden','ok');}const s=d.system||{};setText('sys','IP '+(s.ip||'--')+' | CPU '+(s.cpu??'--')+'% | RAM '+(s.ram??'--')+'% | Temp '+(s.temp??'--')+'°C');setText('weatherText',d.weather?.text||'Wetter lädt ...');renderBoards(d.boards||[]);refreshRadar(false);}catch(e){setStreamStatus('Verbindung wird wiederhergestellt','reconnect');showToast('Verbindung zur App wird wiederhergestellt ...','error');}}
setInterval(pull,2000);pull();setInterval(()=>refreshRadar(true),300000);
function openMenu(){const menu=byId('menu'),btn=byId('menuBtn');if(!menu)return;menu.classList.remove('hidden');btn?.setAttribute('aria-expanded','true');loadConfig().then(()=>byId('cfgStream')?.focus());}
function closeMenu(){const menu=byId('menu'),btn=byId('menuBtn');if(!menu)return;menu.classList.add('hidden');btn?.setAttribute('aria-expanded','false');btn?.focus();}
function fillForm(cfg){currentConfig=cfg;byId('cfgStream').value=cfg.stream?.url||'';byId('cfgLabel').value=cfg.location?.label||'Bielefeld';byId('cfgLat').value=cfg.location?.latitude||52.0302;byId('cfgLon').value=cfg.location?.longitude||8.5325;byId('cfgLayout').value=cfg.ui?.layout_profile||'auto';byId('cfgRadarH').value=cfg.ui?.radar?.height||170;byId('showWeather').checked=!!cfg.ui?.weather?.enabled;byId('showRadar').checked=!!cfg.ui?.radar?.enabled;byId('showTransit').checked=!!cfg.ui?.transit?.enabled;byId('showSystem').checked=!!cfg.ui?.system?.enabled;byId('cfgStops').value=JSON.stringify(cfg.transit?.stops||[],null,2);}
async function loadConfig(){const r=await fetch('/api/config?_='+Date.now(),{cache:'no-store'}),d=await r.json();fillForm(d.config);setStatus('Config: '+d.path);}
function readForm(){const cfg=JSON.parse(JSON.stringify(currentConfig||{}));cfg.stream=cfg.stream||{};cfg.location=cfg.location||{};cfg.ui=cfg.ui||{};cfg.ui.weather=cfg.ui.weather||{};cfg.ui.radar=cfg.ui.radar||{};cfg.ui.transit=cfg.ui.transit||{};cfg.ui.system=cfg.ui.system||{};cfg.transit=cfg.transit||{};const stream=byId('cfgStream').value.trim();if(!stream)throw new Error('Livestream URL fehlt.');cfg.stream.url=stream;cfg.location.label=byId('cfgLabel').value.trim()||'Bielefeld';cfg.location.latitude=parseFloat(byId('cfgLat').value||'52.0302');cfg.location.longitude=parseFloat(byId('cfgLon').value||'8.5325');cfg.ui.layout_profile=byId('cfgLayout').value;cfg.ui.radar.height=Math.max(120,Math.min(260,parseInt(byId('cfgRadarH').value||'170',10)));cfg.ui.weather.enabled=byId('showWeather').checked;cfg.ui.radar.enabled=byId('showRadar').checked;cfg.ui.transit.enabled=byId('showTransit').checked;cfg.ui.system.enabled=byId('showSystem').checked;try{cfg.transit.stops=JSON.parse(byId('cfgStops').value||'[]');}catch(e){throw new Error('Haltestellen JSON ist ungültig.');}return cfg;}
function shortStopTitle(name){const cleaned=String(name||'Haltestelle').replace('Bielefeld','').replace('Bi-','').trim().replace(/^,\s*/,'');return cleaned.split(',')[0].trim()||'Haltestelle';}
function stationToStop(station){return{title:shortStopTitle(station.station_name),station_name:station.station_name,station_id:station.station_id,line_filter:[],nightbus_only:false,hide_if_empty:true,max_rows:3};}
function renderStationResults(results){const root=byId('stationResults');if(!root)return;root.replaceChildren();if(!results||!results.length){const empty=document.createElement('div');empty.className='station-empty';empty.textContent='Keine Haltestelle gefunden.';root.appendChild(empty);return;}results.forEach(station=>{const row=document.createElement('div'),text=document.createElement('div'),name=document.createElement('strong'),meta=document.createElement('span'),btn=document.createElement('button');row.className='station-result';name.textContent=station.station_name||'Haltestelle';meta.textContent=station.station_id?'ID '+station.station_id:'VRR-Haltestelle';text.append(name,meta);btn.className='button button-primary';btn.type='button';btn.textContent='Übernehmen';btn.addEventListener('click',()=>{const cfg=JSON.parse(JSON.stringify(currentConfig||{}));cfg.transit=cfg.transit||{};cfg.transit.stops=[stationToStop(station)];cfg.ui=cfg.ui||{};cfg.ui.transit=cfg.ui.transit||{};cfg.ui.transit.enabled=true;currentConfig=cfg;fillForm(cfg);setStatus('Haltestelle übernommen. Speichern nicht vergessen.','success');showToast('Haltestelle übernommen','success');});row.append(text,btn);root.appendChild(row);});}
async function saveConfig(){try{const cfg=readForm();setStatus('Speichere ...');const r=await fetch('/api/config/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({config:cfg})}),d=await r.json();if(d.ok){currentConfig=cfg;setStatus('Gespeichert: '+d.path,'success');showToast('Einstellungen gespeichert','success');lastRadarRefresh=0;reloadStream();pull();}else{setStatus('Fehler: '+(d.error||'unbekannt'),'error');showToast('Speichern fehlgeschlagen','error');}}catch(e){setStatus('Fehler: '+e.message,'error');showToast(e.message,'error');}}
async function searchStation(){const q=byId('stationQuery').value.trim();if(!q){renderStationResults([]);setStatus('Bitte Suchbegriff eingeben.','error');return;}const btn=byId('stationSearchBtn');if(btn){btn.disabled=true;btn.textContent='Sucht ...';}setStatus('Haltestelle wird gesucht ...');try{const r=await fetch('/api/station/search?q='+encodeURIComponent(q)),d=await r.json();renderStationResults(d.results||[]);setStatus((d.results||[]).length?'Suchergebnis auswählen und übernehmen.':'Keine Haltestelle gefunden.',(d.results||[]).length?undefined:'error');}catch(e){renderStationResults([]);setStatus('Suche fehlgeschlagen: '+e.message,'error');showToast('Haltestellensuche fehlgeschlagen','error');}finally{if(btn){btn.disabled=false;btn.textContent='Suchen';}}}
const liveFrame=byId('live');if(liveFrame){liveFrame.addEventListener('load',()=>{if(currentConfig?.stream?.url){streamLoadedOnce=true;setStreamStatus('Livestream verbunden','ok');}});}
byId('menuBtn')?.addEventListener('click',openMenu);byId('closeMenu')?.addEventListener('click',closeMenu);byId('saveConfig')?.addEventListener('click',saveConfig);byId('reloadConfig')?.addEventListener('click',()=>loadConfig().then(()=>showToast('Config neu geladen','success')));byId('reloadStreamPanel')?.addEventListener('click',reloadStream);byId('streamReload')?.addEventListener('click',reloadStream);byId('stationSearchBtn')?.addEventListener('click',searchStation);byId('settingsForm')?.addEventListener('submit',e=>e.preventDefault());byId('stationQuery')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();searchStation();}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!byId('menu')?.classList.contains('hidden'))closeMenu();});
